import { redirect } from "next/navigation"
import { createServerClient } from "@supabase/ssr"
import { cookies } from "next/headers"
import { MoodCharts } from "@/components/mood/mood-charts"
import { ReportPrintButton } from "@/components/mood/report-print-button"
import { ArrowLeft } from "lucide-react"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export const metadata = {
    title: "Mood Report - MindCare AI",
    description: "Your mental health progress report",
}

export default async function MoodReportPage() {
    const cookieStore = await cookies()
    const sessionToken = cookieStore.get("mindcare_session")?.value

    if (!sessionToken) {
        redirect("/auth/login")
    }

    const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, {
        cookies: {
            getAll() { return cookieStore.getAll() },
            setAll(cookiesToSet) {
                try { cookiesToSet.forEach(({ name, value, options }) => cookieStore.set(name, value, options)) } catch { }
            }
        },
    })

    // Decode session token
    let userId
    try {
        const decoded = Buffer.from(sessionToken, "base64").toString()
        userId = decoded.split(":")[0]
    } catch (e) {
        redirect("/auth/login")
    }

    if (!userId) {
        redirect("/auth/login")
    }

    const { data: profile } = await supabase.from("profiles").select("*").eq("id", userId).single()

    // Fetch last 30 days of logs
    const { data: moodLogs } = await supabase
        .from("mood_logs")
        .select("*")
        .eq("user_id", userId)
        .order("created_at", { ascending: false })
        .limit(30)

    const currentDate = new Date().toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    })

    return (
        <div className="max-w-4xl mx-auto space-y-8 p-4 md:p-8 bg-white min-h-screen text-black">
            {/* Header - No Print */}
            <div className="flex items-center justify-between print:hidden">
                <Link href="/dashboard/mood">
                    <Button variant="ghost">
                        <ArrowLeft className="w-4 h-4 mr-2" /> Back to Dashboard
                    </Button>
                </Link>
                <ReportPrintButton />
            </div>

            {/* Report Header */}
            <div className="border-b-2 border-black pb-6 mb-8">
                <div className="flex items-center justify-between">
                    <div>
                        <h1 className="text-3xl font-bold tracking-tight">Clinical Mood Report</h1>
                        <p className="text-gray-600 mt-2">Generated by MindCare AI</p>
                    </div>
                    <div className="text-right">
                        <div className="font-semibold text-lg">{profile?.full_name || "Patient"}</div>
                        <div className="text-sm text-gray-500">{profile?.email}</div>
                        <div className="text-sm text-gray-500 mt-1">Date: {currentDate}</div>
                    </div>
                </div>
            </div>

            {/* Analytics Section */}
            <div className="space-y-6">
                <h2 className="text-xl font-bold border-b border-gray-200 pb-2">30-Day Overview</h2>

                {/* Chart */}
                <div className="h-[300px] w-full border border-gray-100 rounded-lg p-4 bg-gray-50 print:bg-white print:border-black">
                    <MoodCharts moodLogs={moodLogs || []} />
                </div>
            </div>

            {/* Logs Table */}
            <div className="space-y-4 mt-8">
                <h2 className="text-xl font-bold border-b border-gray-200 pb-2">Detailed Log History</h2>

                <table className="w-full text-left text-sm">
                    <thead className="bg-gray-100 print:bg-gray-200">
                        <tr>
                            <th className="p-3 font-semibold border-b">Date & Time</th>
                            <th className="p-3 font-semibold border-b">Mood</th>
                            <th className="p-3 font-semibold border-b">Intensity</th>
                            <th className="p-3 font-semibold border-b">Primary Emotion</th>
                            <th className="p-3 font-semibold border-b w-1/3">Notes</th>
                        </tr>
                    </thead>
                    <tbody>
                        {moodLogs?.map((log) => (
                            <tr key={log.id} className="border-b hover:bg-gray-50 print:border-gray-300">
                                <td className="p-3 align-top">
                                    {new Date(log.created_at).toLocaleDateString()}
                                    <br />
                                    <span className="text-xs text-gray-500">
                                        {new Date(log.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                    </span>
                                </td>
                                <td className="p-3 align-top font-medium capitalize">{log.mood}</td>
                                <td className="p-3 align-top">
                                    <span className="inline-block px-2 py-1 rounded bg-gray-100 font-semibold print:border print:border-gray-400">
                                        {log.intensity}/10
                                    </span>
                                </td>
                                <td className="p-3 align-top capitalize">{log.emotion || "-"}</td>
                                <td className="p-3 align-top text-gray-600 italic">
                                    "{log.note || "No notes recorded"}"
                                    {(log.emotions && log.emotions.length > 0) && (
                                        <div className="flex flex-wrap gap-1 mt-1">
                                            {log.emotions.map((t: string) => (
                                                <span key={t} className="text-[10px] px-1.5 py-0.5 bg-gray-100 rounded border border-gray-200 print:border-gray-400">
                                                    {t}
                                                </span>
                                            ))}
                                        </div>
                                    )}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>

                {(!moodLogs || moodLogs.length === 0) && (
                    <div className="text-center py-10 text-gray-500 italic">
                        No mood logs found for the selected period.
                    </div>
                )}
            </div>

            {/* Footer */}
            <div className="mt-12 pt-6 border-t border-gray-200 text-center text-xs text-gray-400 print:text-black">
                <p>This report is a summary of self-reported data and is not a clinical diagnosis.</p>
                <p>MindCare AI &copy; {new Date().getFullYear()}</p>
            </div>
        </div>
    )
}
